name = "SurvivalBase"
uuid = "9cb6079b-e021-4662-8a75-9f65bfa286f2"
authors = ["Oskar Laverny <oskar.laverny@univ-amu.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
